services:
  ls-server: 
    build: .
    ports:
      - 8080:8080

  mongo:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass

  nginx-rtmp:
    build:
      context: ./nginx
      args:
        ENABLED_MODULES: rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/index.html:/usr/share/nginx/html/index.html # Keep this if you want the stream to be tested on a locally served nginx html page
    ports:
      - 8000:8000
      - 1936:1935

    develop:
      watch:
        - action: sync
          path: ./nginx.conf
          target: /etc/nginx/