services:
  ls-server: 
    container_name: ls-server
    build: .
    ports:
      - 3333:3333
    depends_on:
      - mongo
    
    develop:
      watch:
        - action: sync
          path: ./*.go
          target: /app

  nginx-rtmp:
    container_name: nginx
    build:
      context: ./nginx
      args:
        ENABLED_MODULES: rtmp
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8000:8000
      - 1936:1935
    depends_on:
      - ls-server

  mongo:
    container_name: database
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass
    ports:
      - 27017:27017